language: scala
scala:
- 2.11.4
jdk:
- oraclejdk8
notifications:
  email: false
  hipchat:
    rooms:
      secure: H2g8rdi7W4ZiU49IGozXTFvaugch84rqp/XiNnIAB1rID4R68p8TV7Khxz8JaitNqu4U4Iw2Z5y0aYJLdu+MyrrMsmpZ1aKvOaVfyDh+oRLpuM+pjsyCrzQVWpnYKFLJ7eesTK5ELx74I/h1tsuM7o8sCgLf5Wf7oDuXP737V20=
    on_success: change
    on_failure: change
    notify: true
deploy:
  provider: heroku
  api_key:
    secure: RGOOvtd08safEwxbopdpJPpTSjbXl0PreR97Lg006EPsZkx5yajJID7873RmxEFTV0mSJf4JD+MfdzPqnRpC9Uys3wiWaPdAHlpnGszOobOq7WRLPUWU+AaaxiE4e/AlZa3suJE4yEMHxa5jL4AeA65k08WErVqo+Sz5b80DdEQ=
  app: neeedo-webapp
  on:
    repo: HTW-Projekt-2014-Commercetools/neeedo-WebApp
